export const data = {
  id: 15,
  userId: 3,
  title: 'test 2',
  seller: 'LabDirect',
  status: 'Pending',
  createdAt: '2024-10-30T20:16:27.408Z',
  updatedAt: '2024-10-30T20:16:27.408Z',
  reagents: [
    {
      id: 3,
      userId: 5,
      name: 'Reagent A',
      structureSmiles: 'CO',
      casNumber: '123-45-67',
      desiredQuantity: 500,
      quantityUnit: 'ml',
      userComments: 'Commenting here...',
      procurementComments: null,
      status: 'Pending',
      createdAt: '2024-10-29T17:12:48.954Z',
      updatedAt: '2024-10-30T20:16:27.408Z',
      orderId: 15,
    },
  ],
};

export const mockOrders = [
  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },  {
    id: 101,
    userId: 201,
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 1,
        userId: 201,
        name: 'Acetone',
        structureSmiles: 'CC(=O)C',
        casNumber: '67-64-1',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
      {
        id: 2,
        userId: 201,
        name: 'Methanol',
        structureSmiles: 'CO',
        casNumber: '67-56-1',
        desiredQuantity: 1000,
        quantityUnit: 'mL',
        userComments: 'Store in a cool place',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-15T10:00:00Z',
        updatedAt: '',
        orderId: 101,
      },
    ],
  },
  {
    id: 102,
    userId: 202,
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    status: 'Pending',
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 3,
        userId: 202,
        name: 'Ethyl Acetate',
        structureSmiles: 'CCOC(=O)C',
        casNumber: '141-78-6',
        desiredQuantity: 200,
        quantityUnit: 'mL',
        userComments: 'Handle with care',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
      {
        id: 4,
        userId: 202,
        name: 'Phenol',
        structureSmiles: 'C1=CC=C(C=C1)O',
        casNumber: '108-95-2',
        desiredQuantity: 100,
        quantityUnit: 'g',
        userComments: 'Wear gloves when handling',
        procurementComments: null,
        status: 'Pending',
        createdAt: '2023-10-18T12:00:00Z',
        updatedAt: '',
        orderId: 102,
      },
    ],
  },
  {
    id: 103,
    userId: 203,
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    status: 'Fulfilled',
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    reagents: [
      {
        id: 5,
        userId: 203,
        name: 'Sodium Chloride',
        structureSmiles: '[Na+].[Cl-]',
        casNumber: '7647-14-5',
        desiredQuantity: 1000,
        quantityUnit: 'g',
        userComments: 'Store in a dry place',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
      {
        id: 6,
        userId: 203,
        name: 'Sulfuric Acid',
        structureSmiles: 'O=S(=O)(O)O',
        casNumber: '7664-93-9',
        desiredQuantity: 500,
        quantityUnit: 'mL',
        userComments: 'Handle with extreme care',
        procurementComments: null,
        status: 'Fulfilled',
        createdAt: '2023-09-20T08:30:00Z',
        updatedAt: '',
        orderId: 103,
      },
    ],
  },
];

