import { Order, Status } from './src/app/pages/orders-list/model/order-model';
import { Category } from './src/app/shared/models/reagent-model';

export const mockOrders: Order[] = [
  {
    title: 'Order 1 - Chemicals',
    seller: 'PharmaPlus',
    id: 101,
    userId: 201,
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '',
    status: Status.pending,
    reagents: [
      {
        name: 'Acetone',
        smiles: 'CC(=O)C',
        cas: '67-64-1',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 300,
        storageId: 1,
        structure: 'C3H6O',
        room: {
          id: 5,
          name: 'Storage Room A',
          description: 'Temperature-controlled storage',
        },
      },
      {
        name: 'Methanol',
        smiles: 'CO',
        cas: '67-56-1',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 750,
        storageId: 2,
        structure: 'CH4O',
        room: {
          id: 5,
          name: 'Storage Room A',
          description: 'Temperature-controlled storage',
        },
      },
    ],
  },
  {
    title: 'Order 2 - Sample Collection',
    seller: 'PharmaPlus',
    id: 102,
    userId: 202,
    createdAt: '2023-10-18T12:00:00Z',
    updatedAt: '',
    status: Status.pending,
    reagents: [
      {
        name: 'Ethyl Acetate',
        smiles: 'CCOC(=O)C',
        cas: '141-78-6',
        category: Category.reagent,
        totalQuantity: 200,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 150,
        storageId: 3,
        structure: 'C4H8O2',
        room: {
          id: 7,
          name: 'Chem Lab Storage',
          description: 'Flammable storage area',
        },
      },
      {
        name: 'Phenol',
        smiles: 'C1=CC=C(C=C1)O',
        cas: '108-95-2',
        category: Category.sample,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 40,
        storageId: 4,
        structure: 'C6H5OH',
        room: {
          id: 7,
          name: 'Chem Lab Storage',
          description: 'Flammable storage area',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
  {
    title: 'Order 3 - Lab Essentials',
    seller: 'LabDirect',
    id: 103,
    userId: 203,
    createdAt: '2023-09-20T08:30:00Z',
    updatedAt: '',
    status: Status.fulfilled,
    reagents: [
      {
        name: 'Sodium Chloride',
        smiles: '[Na+].[Cl-]',
        cas: '7647-14-5',
        category: Category.reagent,
        totalQuantity: 1000,
        package: 'bag',
        quantityUnit: 'g',
        quantityLeft: 500,
        storageId: 5,
        structure: 'NaCl',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
      {
        name: 'Sulfuric Acid',
        smiles: 'O=S(=O)(O)O',
        cas: '7664-93-9',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 200,
        storageId: 6,
        structure: 'H2SO4',
        room: {
          id: 10,
          name: 'General Storage Room',
          description: 'Dry storage',
        },
      },
    ],
  },
  {
    title: 'Order 4 - Experimental Samples',
    seller: 'BioChem Suppliers',
    id: 104,
    userId: 204,
    createdAt: '2023-08-01T15:45:00Z',
    updatedAt: '',
    status: Status.declined,
    reagents: [
      {
        name: 'Hydrogen Peroxide',
        smiles: 'OO',
        cas: '7722-84-1',
        category: Category.reagent,
        totalQuantity: 100,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 60,
        storageId: 7,
        structure: 'H2O2',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
      {
        name: 'Ammonium Nitrate',
        smiles: '[NH4+].[NO3-]',
        cas: '6484-52-2',
        category: Category.sample,
        totalQuantity: 50,
        package: 'bottle',
        quantityUnit: 'g',
        quantityLeft: 25,
        storageId: 8,
        structure: 'NH4NO3',
        room: {
          id: 8,
          name: 'Chemical Lab',
          description: 'Refrigerated',
        },
      },
    ],
  },
  {
    title: 'Order 5 - Organic Solvents',
    seller: 'Pure Chemicals Ltd.',
    id: 105,
    userId: 205,
    createdAt: '2023-07-15T09:15:00Z',
    updatedAt: '',
    status: Status.ordered,
    reagents: [
      {
        name: 'Chloroform',
        smiles: 'ClC(Cl)Cl',
        cas: '67-66-3',
        category: Category.reagent,
        totalQuantity: 500,
        package: 'bottle',
        quantityUnit: 'mL',
        quantityLeft: 100,
        storageId: 9,
        structure: 'CHCl3',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
      {
        name: 'Toluene',
        smiles: 'CC1=CC=CC=C1',
        cas: '108-88-3',
        category: Category.reagent,
        totalQuantity: 300,
        package: 'canister',
        quantityUnit: 'mL',
        quantityLeft: 250,
        storageId: 9,
        structure: 'C7H8',
        room: {
          id: 11,
          name: 'Solvent Storage Room',
          description: 'Ventilated storage',
        },
      },
    ],
  },
];
