export const NewReagentsList = [
  {
    name: 'Mercury Acetate',
    smiles: '',
    cas: '',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: 'Ni-Al Alloy, powder',
    smiles: '',
    cas: '',
    quantity: 0.9,
    package: 'Plactic box',
    units: 'kg',
    quantityLeft: 0.9,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: 'm-iodomenzoic acid',
    smiles: '',
    cas: '',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: 'Benzoic acid',
    smiles: '',
    cas: '',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: '(Oxone monopersulfate)potassium pero-xymonosulfate',
    smiles: '',
    cas: '70693-62-8',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: '3-Bromopropionic acid, 97%',
    smiles: 'OC(=O)CCBr',
    cas: '590-92-1',
    quantity: 0.025,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.025,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: '4-Bromobutyric acid, 97%',
    smiles: 'OC(=O)CCCBr',
    cas: '2623-87-2',
    quantity: 0.01,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.01,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: '5-Bromovaleric acid, 97%',
    smiles: 'OC(=O)CCCCBr',
    cas: '2067-33-6',
    quantity: 0.01,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.01,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: '6-Bromoyexanoic acid, 98%',
    smiles: '[O-]C(=O)CCCCCBr',
    cas: '4224-70-8',
    quantity: 0.025,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.025,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: 'Bromoacetic acid, 98%',
    smiles: 'OC(=O)CBr',
    cas: '79-08-3',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'top right shelf',
  },
  {
    name: 'Potassium Nitrate',
    smiles: '',
    cas: '',
    quantity: 0.5,
    package: 'Plactic box',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Potassium Nitrite',
    smiles: '',
    cas: '',
    quantity: 0.5,
    package: 'Plactic box',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Potassium Iodide',
    smiles: '',
    cas: '',
    quantity: 0.01,
    package: 'Plactic box',
    units: 'kg',
    quantityLeft: 0.01,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Sodium Hydroxide',
    smiles: '',
    cas: '',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Sodium Hydride',
    smiles: '',
    cas: '',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Sodium Sulphite',
    smiles: '',
    cas: '',
    quantity: 0.2,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.2,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: '4-Aminobenzoic acid, 99%',
    smiles: 'Nc1ccc(cc1)C(O)=O',
    cas: '150-13-0',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Sodium hydrogen sulfide monohydrate',
    smiles: '[Na+].[SH-]',
    cas: '16721-80-5',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'Аcetic acid, potassium salt, 97%',
    smiles: '[K+].CC([O-])=O',
    cas: '127-08-2',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom shelf right',
  },
  {
    name: 'L-Tyrosine',
    smiles: '',
    cas: '',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: '4-isobutyl-a-methylphenylacetic acid 99%',
    smiles: 'NC(CS)C(O)=O',
    cas: '1568-7-27-1',
    quantity: 1,
    package: 'Bottle',
    units: 'g',
    quantityLeft: 1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'L-Histidine Hydrochlorid Monohydrate',
    smiles: '',
    cas: '',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'L-Cysteine',
    smiles: '',
    cas: '52-90-4',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'L-Cysteine Hydrochlorid',
    smiles: '',
    cas: '',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: '2-Butanol',
    smiles: 'CC(C)O',
    cas: '78-92-2',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: '3-Bromopyruvic acid',
    smiles: 'OC(=O)C(CBr)=O',
    cas: '598-15-4',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Chloroacetic acid',
    smiles: 'C(Cl)C(=O)O',
    cas: '79-11-8',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium sulfate',
    smiles: '',
    cas: '7757-82-6',
    quantity: 0.1,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.1,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium Acetate',
    smiles: 'CC(=O)[O-].[Na+]',
    cas: '127-09-3',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium Chloride',
    smiles: '',
    cas: '7647-14-5',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium Carbonate',
    smiles: '',
    cas: '497-19-8',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Calcium Chloride',
    smiles: '',
    cas: '10043-52-4',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Barium Sulfate',
    smiles: '',
    cas: '7727-43-7',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Potassium Sulfate',
    smiles: '',
    cas: '7778-80-5',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Potassium Bisulfate',
    smiles: '',
    cas: '7646-93-7',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Copper sulfate',
    smiles: '',
    cas: '7758-99-8',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Potassium bromide',
    smiles: '',
    cas: '7758-02-3',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Bromine',
    smiles: 'Br',
    cas: '7726-95-6',
    quantity: 0.25,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.25,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Calcium Carbonate',
    smiles: '',
    cas: '471-34-1',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Calcium Sulfate',
    smiles: '',
    cas: '7778-18-9',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Barium Chloride',
    smiles: '',
    cas: '10361-72-3',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Calcium Nitrate',
    smiles: '',
    cas: '10124-37-5',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Acetic Acid',
    smiles: 'CC(=O)O',
    cas: '64-19-7',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Methanol',
    smiles: 'CO',
    cas: '67-56-1',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Ethanol',
    smiles: 'CCO',
    cas: '64-17-5',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Dimethyl sulfoxide',
    smiles: 'CS(=O)C',
    cas: '67-68-5',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Diethyl ether',
    smiles: 'CCOCC',
    cas: '60-29-7',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Hexane',
    smiles: 'CCCCCC',
    cas: '110-54-3',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Chloroform',
    smiles: 'ClC(=C(C)C(C)C)C(=O)C',
    cas: '67-66-3',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Dichloromethane',
    smiles: 'C(Cl)C(Cl)C',
    cas: '75-09-2',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Hydrochloric acid',
    smiles: 'Cl',
    cas: '7647-01-0',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Nitric acid',
    smiles: 'O=N(=O)O',
    cas: '7697-37-2',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sulfuric acid',
    smiles: 'OS(=O)(=O)O',
    cas: '7664-93-9',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Phosphoric acid',
    smiles: 'O=P(O)(O)O',
    cas: '7664-38-2',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium bicarbonate',
    smiles: 'CC(=O)[O-].[Na+]',
    cas: '144-55-8',
    quantity: 0.5,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 0.5,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium acetate, trihydrate',
    smiles: 'CC(=O)[O-].[Na+].3H2O',
    cas: '6131-90-4',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
  {
    name: 'Sodium hydroxide, pellets',
    smiles: '',
    cas: '1310-73-2',
    quantity: 1.0,
    package: 'Bottle',
    units: 'kg',
    quantityLeft: 1.0,
    room: 'room 1376',
    location: 'bottom left shelf',
  },
];
