name: E Lab FE Non Prod

on: workflow_dispatch

jobs:
    install-and-validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20' # Specify the Node.js version you want to use

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint

            # - name: Run tests
            #   run: npm run test

            - name: Run build
              run: npm run build

    deploy:
      runs-on: ubuntu-latest
      needs: install-and-validate
      # env:
      #   API_URL: ${{ secrets.API_URL }}

      steps:
        - name: Install OpenVPN
          run: |
            sudo apt update
            sudo apt install -y openvpn openvpn-systemd-resolved

        - name: Checkout code
          uses: actions/checkout@v4
          with:
            path: elab-fe

        # - name: Create .env file
        #   working-directory: elab-fe
        #   run: |
        #     echo "API_URL=${API_URL}" >> .env

        - name: Connect to VPN
          uses: "kota65535/github-openvpn-connect-action@v2"
          with:
            config_file: ./elab-fe/.github/workflows/client.ovpn

        - name: Copy code to VM
          env:
            SSH_KEY: ${{secrets.SSH_KEY}}
            SSH_USER: ${{secrets.SSH_USER}}
            VM_IP: ${{vars.VM_IP}}
          run: |
            echo "${SSH_KEY}" >> /tmp/ssh_key
            chmod 400 /tmp/ssh_key
            scp -o KexAlgorithms=ecdh-sha2-nistp521 -o 'StrictHostKeyChecking no' -i /tmp/ssh_key -r ./elab-fe ${SSH_USER}@$VM_IP:~
        - name: Run latest version
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ vars.VM_IP }}
            username: ${{ secrets.SSH_USER }}
            cipher: ecdh-sha2-nistp521
            key: ${{secrets.SSH_KEY}}
            script: |
              cd ~/elab-fe
              sudo docker compose stop
              sudo docker compose -f docker-compose.non-prod.yml up -d --build
              rm -rf ./.git
